development:
  perform_authentication: false
  asset_server: /pic/

test:
  perform_authentication: false

production:
  perform_authentication: true
  username: admin
  password: secret
  asset_server: /pic/
