development:
  adapter: postgresql
  encoding: utf8
  host: 127.0.0.1
  database: renata
  username: renata
  password: 

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  host: 127.0.0.1
  database: renata
  username: renata
  password: H5XJtueoAwDAAZ7dC2zESO2rJMFaxFPxYxpSqK46Vk


