development:
  address: localhost
  port: 587
  domain: 
  authentication: plain
  user_name: 
  password: 

production:
  address: mail.ezit.hu
  domain: 1xferienhaus.de
  authentication: plain
  user_name: buchung@1xferienhaus.de
  password: 
